export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const ORDER_ITEM = 'ORDER_ITEM';
export const ORDER_ITEM_COUNT = 'ORDER_ITEM_COUNT';
export const INCRESS_ORDER_ITEM = 'INCRESS_ORDER_ITEM';
export const ADD_CHANGE_ORDER_ITEM = 'ADD_CHANGE_ORDER_ITEM';
export const ADD_ORDER_ITEM = 'ADD_ORDER_ITEM';


